services:
  go-app:
    build: ./personal-app
    container_name: personal-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./personal-app:/app
    working_dir: /app
    command: air

